<a href="https://colab.research.google.com/github/Prathambiradr12345/Machine-_learning/blob/main/classification_matrix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#when accuracy score is misleading=imbalanced data

In [ ]:
#precision=true positve /true positve+false positive
#recall=true positve /true positve+false nagative
#f1 score=it is a lower value site

In [1]:
import pandas as pd
import numpy as np
import numpy as np
import pandas as pd
df=pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [4]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [5]:
clf1.fit(x_train,y_train)
clf2.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [6]:
y_prd1=clf1.predict(x_test)
y_prd2=clf2.predict(x_test)

In [7]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_prd1))
print(accuracy_score(y_test,y_prd2))

0.9016393442622951
0.8524590163934426


In [8]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_prd1))
print(classification_report(y_test,y_prd2))

              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61

              precision    recall  f1-score   support

           0       0.96      0.75      0.84        32
           1       0.78      0.97      0.86        29

    accuracy                           0.85        61
   macro avg       0.87      0.86      0.85        61
weighted avg       0.87      0.85      0.85        61



In [9]:
confusion_matrix(y_test,y_prd1)

array([[26,  6],
       [ 0, 29]])

In [10]:
from sklearn.metrics import precision_score,recall_score,f1_score
print(f1_score(y_test,y_prd1))
print(precision_score(y_test,y_prd1))
print(recall_score(y_test,y_prd1))

0.90625
0.8285714285714286
1.0


In [11]:
print(f1_score(y_test,y_prd2))
print(precision_score(y_test,y_prd2))
print(recall_score(y_test,y_prd2))

0.8615384615384616
0.7777777777777778
0.9655172413793104


In [20]:
precision_score(y_test,y_prd2,average=None)


array([0.96      , 0.77777778])

In [21]:
recall_score(y_test,y_prd2,average=None)

array([0.75      , 0.96551724])

In [23]:
#multi class classification=two or more classes
from sklearn.metrics import classification_report
print(classification_report(y_test,y_prd1))
print(classification_report(y_test,y_prd2))

              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61

              precision    recall  f1-score   support

           0       0.96      0.75      0.84        32
           1       0.78      0.97      0.86        29

    accuracy                           0.85        61
   macro avg       0.87      0.86      0.85        61
weighted avg       0.87      0.85      0.85        61

